# Generated by Django 4.1.4 on 2023-01-01 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_ad', '0002_alter_cars_options_remove_cars_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
