# Generated by Django 4.1.4 on 2023-01-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ad', '0004_remove_cars_desc_remove_cars_img_remove_cars_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='contact',
            field=models.CharField(default='contact', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='desc',
            field=models.TextField(default='mileage', max_length=500),
        ),
        migrations.AddField(
            model_name='cars',
            name='img',
            field=models.CharField(default='mileage', max_length=500),
        ),
        migrations.AddField(
            model_name='cars',
            name='make',
            field=models.CharField(default='mileage', max_length=150),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.CharField(default='mileage', max_length=300),
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.CharField(default='mileage', max_length=150),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.CharField(default='mileage', max_length=300),
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.CharField(default='mileage', max_length=150),
        ),
    ]
