# Generated by Django 4.1.4 on 2023-01-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ad', '0005_cars_contact_cars_desc_cars_img_cars_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='contact',
            field=models.CharField(default='Enter contact info here', max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='desc',
            field=models.TextField(default='Enter description here', max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.CharField(default='Enter img link here', max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(default='Enter make here', max_length=150),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.CharField(default='Enter mileage here', max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(default='Enter model here', max_length=150),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(default='Enter price here', max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.CharField(default='Enter year here', max_length=150),
        ),
    ]
