# Generated by Django 4.1.4 on 2023-01-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ad', '0006_alter_cars_contact_alter_cars_desc_alter_cars_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(default='', max_length=150),
        ),
    ]
