# Generated by Django 4.1.4 on 2023-01-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ad', '0007_alter_cars_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='desc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.CharField(default='', max_length=150),
        ),
    ]
