# Generated by Django 4.1.4 on 2023-01-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ad', '0008_alter_cars_contact_alter_cars_desc_alter_cars_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='picture',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cars',
            name='picture1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cars',
            name='picture2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cars',
            name='picture3',
            field=models.CharField(default='', max_length=500),
        ),
    ]
