# Generated by Django 4.1.4 on 2023-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ad', '0009_cars_picture_cars_picture1_cars_picture2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='picture3',
        ),
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.CharField(default='thumbnail', max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='picture',
            field=models.CharField(default='pic', max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='picture1',
            field=models.CharField(default='add extra pic', max_length=500),
        ),
    ]
